### ISSUE TITLE
Internal Components' generator

### ISSUE THREAD

**Issue by manuelitox** [manuelitox/generator-modules#2]
Something as this:

``` sass
@include gen-component('box') {
  @include gen-internal-component('header') {
    @include gen-attribute(background-color, yellow);
   }
}
```

``` css
.box-header {
  background-color: yellow;
}
```
