### ISSUE TITLE
gen-attributes should allow to pass multiple sets of attributes in the same request.

### ISSUE THREAD

**Issue by manuelitox** [manuelitox/generator-modules#4]
#### Sass:

``` sass
$theme: (
  background: red,
  color: green
) !default;

$properties: ( 
  margin: 10px, 
  padding: 10px
) !default;

.foo {
  @include gen-attributes($properties, $theme);
}
```
#### CSS:

``` css
.foo {
  margin: 10px;
  padding: 10px;
  background: red;
  color: green;
}
```
